services:
  kiwix:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - ./data:/data
    restart: unless-stopped
    environment:
      ITEMS: |
          wiktionary  wiktionary_en_all_nopic_
          stack_exchange gardening.stackexchange.com_en_all_
          wikipedia   wikipedia_en_all_maxi_
          gutenberg   gutenberg_en_all_
          zimit       medlineplus.gov_en_all_
          zimit       www.ready.gov_en_
          zimit       lrnselfreliance_en_all_
          other       zimgit-post-disaster_en_
          other       zimgit-water_en_